AWSTemplateFormatVersion: "2010-09-09"
Description: "Sets up Lambda functions for AWS Config rule and auto remediation"

Parameters:
  S3BucketName:
    Type: String
    Description: "Name of the S3 bucket containing Lambda function code"
    Default: "wojciechowski.sh-lambda-registry"

Resources:
  ConfigRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSConfigRulesExecutionRole
      Policies:
        - PolicyName: ConfigRulePermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:GetSerialConsoleAccessStatus
                Resource: "*"

  ConfigRuleLambda:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt ConfigRuleRole.Arn
      Runtime: python3.13
      Handler: rule.lambda_handler
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: rule.zip

  ConfigRulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ConfigRuleLambda.Arn
      Action: lambda:InvokeFunction
      Principal: config.amazonaws.com

Outputs:
  ConfigRuleLambdaArn:
    Description: "ARN of the Config Rule Lambda function"
    Value: !GetAtt ConfigRuleLambda.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ConfigRuleLambdaArn"
