AWSTemplateFormatVersion: "2010-09-09"
Description: "Sets up an SSM document for Config remediation"

Resources:
  SSMAutomationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ssm.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: RemediationPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DisableSerialConsoleAccess
                Resource: "*"

  SSMAutomationDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Automation
      DocumentFormat: YAML
      Content:
        schemaVersion: '0.3'
        description: "Disable EC2 serial console access"
        assumeRole: !GetAtt SSMAutomationRole.Arn
        mainSteps:
          - name: DisableSerialConsoleAccess
            action: aws:executeAwsApi
            isEnd: true
            inputs:
              Service: ec2
              Api: DisableSerialConsoleAccess

Outputs:
  SSMAutomationDocumentName:
    Description: "Name of the SSM Automation Document"
    Value: !Ref SSMAutomationDocument
    Export:
      Name: !Sub "${AWS::StackName}-SSMAutomationDocumentName"

  SSMAutomationRoleArn:
    Description: "ARN of the SSM Automation IAM Role"
    Value: !GetAtt SSMAutomationRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SSMAutomationRoleArn"